name = "Dartis-Craft - Stargate Network 2.0.6 - AIO Base Modpack - 1.12.2"
author = "Dartis-Craft"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18b89dce5d579947767e3b9120de2012ba49e287aa713f8076592c27ddba2685"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
